variables:
  ml-ws-connection: 'aml-demo' # Workspace Service Connection name
  ml-ws: 'aml-demo' # AML Workspace name
  ml-rg: 'aml-demo' # AML resource Group name
  ml-path: 'model/' # Model directory path in repo
  ml-model-name: 'brain-segmentation-pytorch' # Model name
  ml-aks-name: 'aks-gpu-prod' # AKS cluster name

trigger: none

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: AzureCLI@2
  displayName: 'Install AML CLI'
  inputs:
    azureSubscription: $(ml-ws-connection)
    scriptLocation: inlineScript
    scriptType: bash
    inlineScript: |
      az extension add -n azure-cli-ml

- task: AzureCLI@2
  displayName: 'Attach folder to workspace'
  inputs:
    azureSubscription: $(ml-ws-connection)
    workingDirectory: $(ml-path)
    scriptLocation: inlineScript
    scriptType: bash
    inlineScript: |
      az ml folder attach -w $(ml-ws) -g $(ml-rg)

- task: AzureCLI@2
  displayName: 'Deploy model to ACI for QA'
  inputs:
    azureSubscription: $(ml-ws-connection)
    workingDirectory: $(ml-path)
    scriptLocation: inlineScript
    scriptType: bash
    inlineScript: |
      LATEST_VERSION=`az ml model list -n $(ml-model-name) --query '[0].version'`
      az ml model deploy -n brain-segmentation-aci -m $(ml-model-name):$LATEST_VERSION --ic config/inference-config.yml --dc config/deployment-config-aci.yml --overwrite

# Add potential automated tests

- task: AzureCLI@2
  displayName: 'Deploy model to AKS for Production'
  inputs:
    azureSubscription: $(ml-ws-connection)
    workingDirectory: $(ml-path)
    scriptLocation: inlineScript
    scriptType: bash
    inlineScript: |
      LATEST_VERSION=`az ml model list -n $(ml-model-name) --query '[0].version'`
      az ml model deploy -n brain-segmentation-aks --ct $(ml-aks-name) -m $(ml-model-name):$LATEST_VERSION --ic config/inference-config-gpu.yml --dc config/deployment-config-aks.yml  --overwrite
