variables:
  ml-ws-connection: 'aml-demo' # Workspace Service Connection name
  ml-ws: 'aml-demo' # AML Workspace name
  ml-rg: 'aml-demo' # AML resource Group name
  ml-ct: 'gpu-train-nc24r' # AML Compute cluster name
  ml-path: 'model/' # Model directory path in repo
  ml-exp: 'brain-segmentation-pytorch' # Experiment name
  ml-model-name: 'brain-segmentation-pytorch' # Model name
  ml-dataset: 'lgg-mri-segmentation' # Dataset name

trigger: none

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: AzureCLI@2
  displayName: 'Install AML CLI'
  inputs:
    azureSubscription: $(ml-ws-connection)
    scriptLocation: inlineScript
    scriptType: 'bash'
    inlineScript: 'az extension add -n azure-cli-ml'

- task: AzureCLI@2
  displayName: 'Attach folder to workspace'
  inputs:
    azureSubscription: $(ml-ws-connection)
    workingDirectory: $(ml-path)
    scriptLocation: inlineScript
    scriptType: 'bash'
    inlineScript: 'az ml folder attach -w $(ml-ws) -g $(ml-rg)'
  
- task: AzureCLI@2
  displayName: 'Train model'
  inputs:
    azureSubscription: $(ml-ws-connection)
    workingDirectory: $(ml-path)
    scriptLocation: inlineScript
    scriptType: 'bash'
    inlineScript: 'az ml run submit-script -c config/train --ct $(ml-ct) -e $(ml-exp) -t run.json'

# Add potential approval step before registration of model

- task: AzureCLI@2
  displayName: 'Register model'
  inputs:
    azureSubscription: $(ml-ws-connection)
    workingDirectory: $(ml-path)
    scriptLocation: inlineScript
    scriptType: 'bash'
    inlineScript: 'az ml model register -n $(ml-model-name) -f run.json --asset-path outputs/unet.pt -t model.json'
